version: '3'

services:
  dump1090:
    build: dump1090
    image: dennis14e/ft-dump1090
    restart: unless-stopped
    ports:
      - "8080:8080"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - GMAP_STYLE=new
      - GMAP_CENTER_LAT=52.518611
      - GMAP_CENTER_LNG=13.408333

  fr24feed:
    build: fr24feed
    image: dennis14e/ft-fr24feed
    restart: unless-stopped
    depends_on:
      - dump1090
    ports:
      - "8754:8754"
    environment:
    - SHARING_KEY=
