version: '3'

services:
  readsb:
    # build: readsb
    image: flighttracker/readsb:latest
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - DEVICE_TYPE=rtlsdr
      - DEVICE=
      - GAIN=-10
      - PPM=0
      - NET_RO_SIZE=1200
      - NET_RO_INTERVAL=0.1
      - NET_RO_PORT=30002
      - NET_SBS_PORT=30003
      - NET_BO_PORT=30005
      - UUID=

  # optional
  readsb-web:
    # build: readsb-web
    image: flighttracker/readsb-web:latest
    restart: unless-stopped
    depends_on:
      - readsb
    ports:
      - "80:80"
    environment:
      - CENTER_LAT=
      - CENTER_LNG=
      - CENTER_RADIUS=

  # optional
  fr24feed:
    # build: fr24feed
    image: flighttracker/fr24feed:latest
    restart: unless-stopped
    depends_on:
      - readsb
    ports:
      - "8754:8754"
    environment:
      - SHARING_KEY=
      - DUMP1090_HOST=readsb:30002

  # optional
  pfclient:
    # build: pfclient
    image: flighttracker/pfclient:latest
    restart: unless-stopped
    depends_on:
      - readsb
    ports:
      - "30053:30053"
    environment:
      - SHARING_KEY=
      - DUMP1090_HOST=readsb
      - DUMP1090_PORT=30002
      - LAT=
      - LON=

#  # optional
#  adsb2influx:
#    # build: adsb2influx
#    image: flighttracker/adsb2influx:latest
#    restart: unless-stopped
#    depends_on:
#      - readsb
#    environment:
#      - DUMP1090_HOST=readsb
#      - DUMP1090_PORT=30003
#      - INFLUX_URL=
#      - INFLUX_TOKEN=
#      - INFLUX_ORG=
#      - INFLUX_BUCKET=adsb
#      - SEND_INTERVAL=60
