version: '3'

services:
  dump1090:
    build: dump1090
    restart: unless-stopped
    privileged: true
    ports:
      - "8080:8080"
    devices:
      - /dev/bus/usb:/dev/bus/usb

  fr24feed:
    build: fr24feed
    restart: unless-stopped
    depends_on:
      - dump1090
    ports:
      - "8754:8754"
