version: '3'

services:
  readsb:
    # build: readsb
    image: flighttracker/readsb:latest
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb

  # optional
  web-light:
    # build: web-light
    image: flighttracker/web-light:latest
    restart: unless-stopped
    depends_on:
      - readsb
    ports:
      - "80:80"
    environment:
      - CENTER_LAT=
      - CENTER_LNG=
      - CENTER_RADIUS=

  # optional
  fr24feed:
    # build: fr24feed
    image: flighttracker/fr24feed:latest
    restart: unless-stopped
    depends_on:
      - readsb
    ports:
      - "8754:8754"
    environment:
      - SHARING_KEY=
      - DUMP1090_HOST=readsb:30002

#  # optional
#  adsb2influx:
#    # build: adsb2influx
#    image: flighttracker/adsb2influx:latest
#    restart: unless-stopped
#    depends_on:
#      - readsb
#    environment:
#      - DUMP1090_HOST=readsb
#      - DUMP1090_PORT=30003
#      - INFLUX_URL=
#      - INFLUX_TOKEN=
#      - INFLUX_ORG=
#      - INFLUX_BUCKET=adsb
#      - SEND_INTERVAL=60
