name: Build pull request images

on:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      DOCKER_HUB_ORGANISATION: flighttracker
      PLATFORMS: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386
    strategy:
      fail-fast: false
      matrix:
        DOCKERIMAGE:
          - adsb2influx
          - dump1090
          - fr24feed
          - mlat-client
          - readsb
          - web-light
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.DOCKERIMAGE }}
          file: ${{ matrix.DOCKERIMAGE }}/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          pull: true
          push: false
          tags: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ matrix.DOCKERIMAGE }}:${{ github.sha }}
