name: Build develop images

on:
  push:
    branches:
      - develop
      - 'features/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      GIT_BRANCH: ""
      DOCKER_HUB_USERNAME: dennis14e
      DOCKER_HUB_ORGANISATION: flighttracker
      PLATFORMS: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386
    strategy:
      fail-fast: false
      matrix:
        DOCKERIMAGE:
          - adsb2influx
          - dump1090
          - fr24feed
          - readsb
    steps:
      - name: Set GIT_BRANCH
        run: echo GIT_BRANCH="$(${GITHUB_REF#refs/heads/} | tr _/ -)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.DOCKERIMAGE }}-${{ env.GIT_BRANCH }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.DOCKERIMAGE }}-${{ env.GIT_BRANCH }}-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.DOCKERIMAGE }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          file: ${{ matrix.DOCKERIMAGE }}/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          pull: true
          push: true
          tags: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ matrix.DOCKERIMAGE }}:${{ env.GIT_BRANCH }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
