name: Build develop images

on:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      GIT_BRANCH: ""
      GITHUB_REPO_OWNER: Dennis14e
      DOCKER_HUB_USERNAME: dennis14e
      DOCKER_HUB_ORGANISATION: flighttracker
      QEMU_PLATFORMS: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386
    strategy:
      fail-fast: false
      matrix:
        DOCKER_IMAGE:
          - adsb2influx
          - dump1090
          - fr24feed
          - mlat-client
          - readsb
          - readsb-web
          - uat2esnt
    steps:
      - name: Set GIT_BRANCH
        run: echo "GIT_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr _/ -)" >> $GITHUB_ENV

      - name: Set GIT_BRANCH to edge if main
        if: env.GIT_BRANCH == 'main'
        run: echo "GIT_BRANCH=edge" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Set up cache
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.DOCKER_IMAGE }}-${{ env.GIT_BRANCH }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.DOCKER_IMAGE }}-${{ env.GIT_BRANCH }}-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: ${{ env.QEMU_PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v3.4.1
        with:
          images: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ matrix.DOCKER_IMAGE }}
          flavor: latest=false
          tags: type=raw,value=${{ env.GIT_BRANCH }}

      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ${{ matrix.DOCKER_IMAGE }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          file: ${{ matrix.DOCKER_IMAGE }}/Dockerfile
          platforms: ${{ env.QEMU_PLATFORMS }}
          pull: true
          push: ${{ github.repository_owner == env.GITHUB_REPO_OWNER }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
