name: Build pull request images

on:
  pull_request_target:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      DOCKER_HUB_ORGANISATION: flighttracker
      QEMU_PLATFORMS: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386
    strategy:
      fail-fast: false
      matrix:
        DOCKER_IMAGE:
          - adsb2influx
          - dump1090
          - fr24feed
          - mlat-client
          - readsb
          - readsb-web
          - uat2esnt
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
        with:
          platforms: ${{ env.QEMU_PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ matrix.DOCKER_IMAGE }}
          flavor: latest=false
          tags: type=ref,event=pr

      - name: Build and push
        uses: docker/build-push-action@v2.10.0
        with:
          context: ${{ matrix.DOCKER_IMAGE }}
          file: ${{ matrix.DOCKER_IMAGE }}/Dockerfile
          platforms: ${{ env.QEMU_PLATFORMS }}
          pull: true
          push: false
          tags: ${{ steps.meta.outputs.tags }}
